### ISSUE TITLE
Unable to pull container images

### ISSUE THREAD

**Issue by timbrd** [digitalist-se/matomo-kubernetes#11]
When deploying the helm chart, I get a "401 Unauthorized" error for all the container images. The URL of the matomo image is `registry.wklive.net:5000/matomo/base:3-14-1-php7-4-15-fpm-alpine3-12-4cc32ec6`.

Is this on purpose or an error?

**Comment by jorgeuos** [comment]
Hi, sorry for the late response. Didn't see this until now.  
Yes, the matomo image is just a placeholder, an example if you will. We use this repo as a base and put overrides in a project specifik repo. See the README(yes I know! We need to update the readme). https://github.com/digitalist-se/matomo-kubernetes#create-a-new-project

## TL;DR
You could try to replace:
```
registry.wklive.net:5000/matomo/base:3-14-1-php7-4-15-fpm-alpine3-12-4cc32ec6
```
with:
```
matomo:4.6.2-fpm-alpine
```
To get the latest official image.


## Explained

Because we're using tag based releases nowadays, you can refer to this repo, in your `PROJECT/NAMESPACE/matomo/requirements.yaml` like this:
```
dependencies:
  - name: matomo
    version: 9.1.81
    repository: https://digitalist-se.github.io/matomo-kubernetes
```

And in your `PROJECT/NAMESPACE/matomo/`:
```
apiVersion: v1
appVersion: "4.6.2"
description: A Helm chart for Matomo.
name: matomo
version: 9.1.81
```

And then you put your overrides in your `PROJECT/NAMESPACE/matomo/values.yaml`, like this:
```
matomo:
  namespace: AWESOME_NAMESPACE
  matomo:
    image: matomo:4.6.2-fpm-alpine
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "0.8"
        memory: 128Mi
...
```


I'm not sure which repo Matomo folks are tracking, because the [matomo-org/docker](https://github.com/matomo-org/docker) repo, doesn't update as frequently as the [docker hub](https://hub.docker.com/_/matomo?tab=tags) releases. But it's a good boilerplate.

We build our own image with dependencies for our use cases.

E.g The DB-IP or MaxMind GeoIP Reader, which requires a registered account, but it's free.
Read more [here](https://matomo.org/faq/how-to/faq_163/).

Hope you solved your issue.
